In [1]:
import numpy as np
import csv

Pi =  3.14159
C = 0.011
g = 9.8

t = 0. 
xc = 0.
yc = 0.                 #intial conditions
vx = 5*np.cos(Pi/4.)
vy = 5*np.sin(Pi/4)
step =0.1

x = [xc,yc]
x=np.array(x)
v = [vx,vy]  #v definition
v=np.array(v)
a = -C*np.sqrt(v[0]**2+v[1]**2)*v - g*v  # a definition

with open('euler.csv', 'w', newline='') as file:
    while t < 10.:
        data = []
        #data = data.append(t)
        data = np.append(x,v)
        data = np.array_str(data)
        print(data)
        
        file.write(data)
        file.write('\n')
            
        x += step * v
        v += step * a 
        a = -C*np.sqrt(v[0]**2+v[1]**2)*v-g*v          #euler_methods
        t += step
    
file.close()
    
    

    


[0.         0.         3.53553625 3.53553156]
[0.35355363 0.35355316 0.05126528 0.05126521]
[0.35868015 0.35867968 0.00102122 0.00102122]
[3.58782274e-01 3.58781798e-01 2.04227198e-05 2.04226927e-05]
[3.58784317e-01 3.58783841e-01 4.08453747e-07 4.08453205e-07]
[3.58784358e-01 3.58783881e-01 8.16907468e-09 8.16906384e-09]
[3.58784358e-01 3.58783882e-01 1.63381494e-10 1.63381277e-10]
[3.58784358e-01 3.58783882e-01 3.26762987e-12 3.26762554e-12]
[3.58784358e-01 3.58783882e-01 6.53525974e-14 6.53525107e-14]
[3.58784358e-01 3.58783882e-01 1.30705195e-15 1.30705021e-15]
[3.58784358e-01 3.58783882e-01 2.61410390e-17 2.61410043e-17]
[3.58784358e-01 3.58783882e-01 5.22820779e-19 5.22820086e-19]
[3.58784358e-01 3.58783882e-01 1.04564156e-20 1.04564017e-20]
[3.58784358e-01 3.58783882e-01 2.09128312e-22 2.09128034e-22]
[3.58784358e-01 3.58783882e-01 4.18256623e-24 4.18256069e-24]
[3.58784358e-01 3.58783882e-01 8.36513247e-26 8.36512137e-26]
[3.58784358e-01 3.58783882e-01 1.67302649e-27 1.67302427