In [1]:
from numpy import array

a = array([1,2,3,4],int)
b = array([2,4,6,8],int)

print(b/a+1) #float np.array [3,3,3,3]
print(b/(a+1)) #float np.array [1.0,1.2,1.5,1.6]
print(1/a) #float np.array [1,0.5,0.3333,0.25]

[3. 3. 3. 3.]
[1.         1.33333333 1.5        1.6       ]
[1.         0.5        0.33333333 0.25      ]


In [2]:
from numpy import array

c = array([3,4,5],int)
d = c
c[0] = 4
print(c)
print(d)

#This porblem happens with lists as well

[4 4 5]
[4 4 5]


In [4]:
c = [3,4,5]
print(c)
print(type(c))

c = array(c,int)

print(type(c))
print(c)

#the array() function can reuse the memory

[3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
[3 4 5]


In [6]:
from numpy import array

c = array([3,4,5],float)
d = c + 2

print(c,d)

[3. 4. 5.] [5. 6. 7.]
